
server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: first-service
#          uri: http://localhost:8081/
          uri: lb://FIRST-SERVICE # eureka server's application name
          filters:
#            - AddRequestHeader=first-request, first-request-header2
#            - AddResponseHeader=first-response, first-response-header2
            - CustomFilter
          predicates:
            - Path=/first-service/**
        - id: second-service
#          uri: http://localhost:8085/
          uri: lb://SECOND-SERVICE
          filters:
#            - AddRequestHeader=second-request, second-request-header2
#            - AddResponseHeader=second-response, second-response-header2
            - CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Logging Proceed...
                preLogger: true
                postLogger: true
          predicates:
            - Path=/second-service/**
        # This is for e-commerce service practice information
#        - id: user-service
#          uri: lb://USER-SERVICE # eureka server's application name
#          predicates:
#            - Path=/user-service/**

        - id: user-service
          uri: lb://USER-SERVICE # eureka server's application name
          predicates:
            - Path=/user-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: user-service
          uri: lb://USER-SERVICE # eureka server's application name
          predicates:
            - Path=/user-service/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: user-service
          uri: lb://USER-SERVICE # eureka server's application name
          predicates:
            - Path=/user-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        #user-service's actuator
        - id: user-service
          uri: lb://USER-SERVICE # eureka server's application name
          predicates:
            - Path=/user-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: catalog-service
          uri: lb://CATALOG-SERVICE # eureka server's application name
          predicates:
            - Path=/catalog-service/**

        - id: order-service
          uri: lb://ORDER-SERVICE # eureka server's application name
          predicates:
            - Path=/order-service/**
    # properties for spring cloud config server
#    config:
#      uri: http://localhost:8888
#      name: ecommerce
logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace

#token:
#  secret: "user-service"